/*
  Suggestion vocabularies for the predictive grid cells (Port of Loading / Port of Discharge /
  Last CY). Embedded as static constants — same approach as CARRIER_CODES in rateGrid.jsx — so
  there's no runtime fetch. Curated from the original `textCompletion.csv` reference (now removed);
  edit these arrays directly to add/remove suggestions. Free text is still allowed at the cell, so
  a location not listed here can still be typed.
*/

export const PORTS_OF_LOADING = [
  'Bangkok, Thailand',
  'Barranquilla, Colombia',
  'Cai Mep, Vietnam',
  'Cartagena, Colombia',
  'Dalian, China',
  'Guangzhou, China',
  'Hai Phong, Vietnam',
  'Ho Chi Minh, Vietnam',
  'Hong Kong, Hong Kong',
  'Jebel Ali, United Arab Emirates',
  'Kaohsiung, Taiwan',
  'Karachi, Pakistan',
  'Laem Chabang, Thailand',
  'Manila, Philippines',
  'Mundra, India',
  'Nhava Sheva, India',
  'Ningbo, China',
  'Phnom Penh, Cambodia',
  'Pipavav, India',
  'Port Qasim, Pakistan',
  'Puerto Barrios, Guatemala',
  'Puerto Quetzal, Guatemala',
  'Qingdao, China',
  'Semarang, Indonesia',
  'Shanghai, China',
  'Sihanoukville, Cambodia',
  'Vung Tau, Vietnam',
  'Xiamen, China',
]

export const PORTS_OF_DISCHARGE = [
  'Baltimore, MD',
  'Boston, MA',
  'Charleston, SC',
  'Chicago, IL',
  'Cleveland, OH',
  'Fort Lauderdale, FL',
  'Houston, TX',
  'Jacksonville, FL',
  'Long Beach, CA',
  'Los Angeles, CA',
  'Louisville, KY',
  'Miami, FL',
  'Nashville, TN',
  'New York, NY',
  'Norfolk, VA',
  'Oakland, CA',
  'Prince Rupert, BC',
  'Savannah, GA',
  'Seattle, WA',
  'Tacoma, WA',
  'Tampa, FL',
  'Vancouver, BC',
]

export const LAST_CY_OPTIONS = [
  'Atlanta, GA',
  'Aurora, IL',
  'Baltimore, MD',
  'Boston, MA',
  'Charleston, SC',
  'Chicago, IL',
  'Cincinnati, OH',
  'Cleveland, OH',
  'Columbus, OH',
  'Dallas, TX',
  'Denver, CO',
  'Detroit, MI',
  'Fort Lauderdale, FL',
  'Fort Worth, TX',
  'Houston, TX',
  'Jacksonville, FL',
  'Kansas City, KS',
  'Long Beach, CA',
  'Los Angeles, CA',
  'Louisville, KY',
  'Memphis, TN',
  'Miami, FL',
  'Montreal, QC',
  'Nashville, TN',
  'New York, NY',
  'Norfolk, VA',
  'Oakland, CA',
  'Salt Lake City, UT',
  'Savannah, GA',
  'Seattle, WA',
  'Tacoma, WA',
  'Tampa, FL',
]
